### ISSUE TITLE
3.3.3 (test) not working properly?

### ISSUE THREAD

**Issue by vbebber** [loqed-nl/homey-app#28]
I have been trying to get version 3.3.3 working for a while now, but I'm not succeeding.

I uninstalled both the device and then the app. Then reinstalled everything and adjusted the flows again.

I am not getting the correct status back (at least the flows are not triggered on this), touch to connect on/off and string from mailbox both does not work.

What am I doing wrong?

**Comment by XeroxQ** [comment]
Please install 3.4.* to resolve multiple issues.

The extras, like Touch to Connect and Mailbox string, are not working correctly yet for everyone/every-lock, we are working on it!

**Comment by XeroxQ** [comment]
It turnes out that some users have old Keys enabled from a previous OAuth version.
These old API Keys need to be removed by the user.

Because of security reasons, only the owner can remove those.

If your Settings (through Homey App), like Twists assist or Guest Access Mode (Touwtje) cannot be set through the Homey app, please follow these steps:

Goto [https://app.loqed.com/ 5](https://app.loqed.com/)
Login.
Goto API.
Scroll down to the API Keys section.
Delete all API Keys for all locks (named Homey).
Goto a/one Lock in the Homey App and press Repair.
After this, all locks (and there settings) should work!

If you still experience issues, please let me know!
